-- =====================================================================
-- Tabel staging data mentah: WBS, GC, OHC (PTPN IV Reg V)
-- Menampung SELURUH kolom file db_wbs.xlsx / db_gc.xlsx / db_ohc.xlsx.
-- Setara dengan migration 2026_06_13_090000_create_raw_source_tables.php
-- (lebih disarankan menjalankan: php artisan migrate)
-- =====================================================================

-- ---------- DB WBS (raw, lengkap; pengganti db_wbs ringkas) ----------
CREATE TABLE IF NOT EXISTS `db_wbs_raw` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `batch_id` BIGINT UNSIGNED NULL,
  `plant_code` VARCHAR(12) NULL,
  `company_code` VARCHAR(20) NULL,
  `plant` VARCHAR(20) NULL,
  `plant_desc` VARCHAR(150) NULL,
  `divisi_afdeling` VARCHAR(30) NULL,
  `blok` VARCHAR(30) NULL,
  `status_blok` VARCHAR(20) NULL,
  `tahun_tanam` VARCHAR(10) NULL,
  `komoditi` VARCHAR(10) NULL,
  `period` SMALLINT NULL,
  `project` VARCHAR(60) NULL,
  `wbs` VARCHAR(60) NULL,
  `wbs_desc` VARCHAR(150) NULL,
  `fase` VARCHAR(20) NULL,
  `group_aktifitas` VARCHAR(30) NULL,
  `group_desc` VARCHAR(150) NULL,
  `aktifitas` VARCHAR(30) NULL,
  `job_name` VARCHAR(150) NULL,
  `hierarchy_area` VARCHAR(60) NULL,
  `cost_center` VARCHAR(30) NULL,
  `cc_desc` VARCHAR(150) NULL,
  `partner_cctr` VARCHAR(30) NULL,
  `partner_cctr_desc` VARCHAR(150) NULL,
  `cost_element` VARCHAR(30) NULL,
  `cost_element_desc` VARCHAR(150) NULL,
  `value` DECIMAL(22,2) NULL,
  `currency` VARCHAR(10) NULL,
  `material` VARCHAR(40) NULL,
  `mat_desc` VARCHAR(150) NULL,
  `qty` DECIMAL(22,4) NULL,
  `uom` VARCHAR(20) NULL,
  `object_num` VARCHAR(40) NULL,
  `object_type` VARCHAR(20) NULL,
  `profit_center` VARCHAR(30) NULL,
  `value_type` VARCHAR(20) NULL,
  `reference_procedure` VARCHAR(40) NULL,
  `order_no` VARCHAR(40) NULL,
  `order_type` VARCHAR(20) NULL,
  `order_category` VARCHAR(20) NULL,
  `order_desc` VARCHAR(150) NULL,
  `hectare_planted` DECIMAL(16,4) NULL,
  `co_business_transaction` VARCHAR(20) NULL,
  `mapping_cogm` VARCHAR(60) NULL,
  `klasifikasi` VARCHAR(60) NULL,
  `kode` VARCHAR(40) NULL,
  `pekerjaan_pb712_ii` VARCHAR(150) NULL,
  `pekerjaan_pb7_i` VARCHAR(150) NULL,
  `source` VARCHAR(40) NULL,
  `keterangan` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  KEY `db_wbs_raw_batch_id_index` (`batch_id`),
  KEY `db_wbs_raw_plant_code_index` (`plant_code`),
  KEY `idx_wbs_raw` (`batch_id`,`komoditi`,`plant_code`,`period`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- DB GC (raw) ----------
CREATE TABLE IF NOT EXISTS `db_gc` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `batch_id` BIGINT UNSIGNED NULL,
  `plant_code` VARCHAR(12) NULL,
  `cost_center` VARCHAR(30) NULL,
  `co_object_name` VARCHAR(150) NULL,
  `business_transaction` VARCHAR(20) NULL,
  `document_number` VARCHAR(40) NULL,
  `ref_document_number` VARCHAR(40) NULL,
  `cost_element` VARCHAR(30) NULL,
  `cost_element_name` VARCHAR(150) NULL,
  `period` SMALLINT NULL,
  `posting_date` VARCHAR(20) NULL,
  `value_obj_crcy` DECIMAL(22,2) NULL,
  `total_quantity` DECIMAL(22,4) NULL,
  `posted_uom` VARCHAR(20) NULL,
  `name` VARCHAR(150) NULL,
  `user_name` VARCHAR(40) NULL,
  `material` VARCHAR(40) NULL,
  `material_description` VARCHAR(150) NULL,
  `reference_procedure` VARCHAR(40) NULL,
  `dr_cr_indicator` VARCHAR(5) NULL,
  `reference_key` VARCHAR(60) NULL,
  `partner_object_class` VARCHAR(40) NULL,
  `object_type` VARCHAR(30) NULL,
  `partner_object_name` VARCHAR(150) NULL,
  `partner_object_type` VARCHAR(40) NULL,
  `offsetting_account` VARCHAR(40) NULL,
  `name_offsetting_account` VARCHAR(150) NULL,
  `name_offsetting_account_2` VARCHAR(150) NULL,
  `document_header_text` VARCHAR(150) NULL,
  `partner_object` VARCHAR(60) NULL,
  `partner_object_type3` VARCHAR(40) NULL,
  `partner_cctr` VARCHAR(30) NULL,
  `source_object` VARCHAR(60) NULL,
  `source_object_name` VARCHAR(150) NULL,
  `origin_obj_type` VARCHAR(40) NULL,
  `source_object_type` VARCHAR(40) NULL,
  `cost_element_descr` VARCHAR(150) NULL,
  `plant` VARCHAR(20) NULL,
  `afdeling` VARCHAR(30) NULL,
  `kode` VARCHAR(40) NULL,
  `pekerjaan_pb712_ii` VARCHAR(150) NULL,
  `klasifikasi` VARCHAR(60) NULL,
  `pekerjaan_pb7_i` VARCHAR(150) NULL,
  `komoditi` VARCHAR(10) NULL,
  `unit_kerja` VARCHAR(150) NULL,
  `gc` VARCHAR(60) NULL,
  PRIMARY KEY (`id`),
  KEY `db_gc_batch_id_index` (`batch_id`),
  KEY `db_gc_plant_code_index` (`plant_code`),
  KEY `idx_gc` (`batch_id`,`komoditi`,`plant_code`,`period`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- DB OHC (raw) ----------
CREATE TABLE IF NOT EXISTS `db_ohc` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `batch_id` BIGINT UNSIGNED NULL,
  `plant_code` VARCHAR(12) NULL,
  `cost_center` VARCHAR(30) NULL,
  `co_object_name` VARCHAR(150) NULL,
  `business_transaction` VARCHAR(20) NULL,
  `document_number` VARCHAR(40) NULL,
  `ref_document_number` VARCHAR(40) NULL,
  `cost_element` VARCHAR(30) NULL,
  `cost_element_name` VARCHAR(150) NULL,
  `period` SMALLINT NULL,
  `posting_date` VARCHAR(20) NULL,
  `value_obj_crcy` DECIMAL(22,2) NULL,
  `total_quantity` DECIMAL(22,4) NULL,
  `posted_uom` VARCHAR(20) NULL,
  `name` VARCHAR(150) NULL,
  `user_name` VARCHAR(40) NULL,
  `material` VARCHAR(40) NULL,
  `material_description` VARCHAR(150) NULL,
  `reference_procedure` VARCHAR(40) NULL,
  `dr_cr_indicator` VARCHAR(5) NULL,
  `reference_key` VARCHAR(60) NULL,
  `partner_object_class` VARCHAR(40) NULL,
  `object_type` VARCHAR(30) NULL,
  `partner_object_name` VARCHAR(150) NULL,
  `partner_object_type` VARCHAR(40) NULL,
  `offsetting_account` VARCHAR(40) NULL,
  `name_offsetting_account` VARCHAR(150) NULL,
  `name_offsetting_account_2` VARCHAR(150) NULL,
  `document_header_text` VARCHAR(150) NULL,
  `partner_object` VARCHAR(60) NULL,
  `partner_object_type3` VARCHAR(40) NULL,
  `partner_cctr` VARCHAR(30) NULL,
  `source_object` VARCHAR(60) NULL,
  `source_object_name` VARCHAR(150) NULL,
  `origin_obj_type` VARCHAR(40) NULL,
  `source_object_type` VARCHAR(40) NULL,
  `cost_element_descr` VARCHAR(150) NULL,
  `plant` VARCHAR(20) NULL,
  `lock` VARCHAR(20) NULL,
  `kode` VARCHAR(40) NULL,
  `pekerjaan_pb712_ii` VARCHAR(150) NULL,
  `klasifikasi` VARCHAR(60) NULL,
  `pekerjaan_pb7_i` VARCHAR(150) NULL,
  `komoditi` VARCHAR(10) NULL,
  `unit_kerja` VARCHAR(150) NULL,
  `pekerjaan_pb712_iii` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  KEY `db_ohc_batch_id_index` (`batch_id`),
  KEY `db_ohc_plant_code_index` (`plant_code`),
  KEY `idx_ohc` (`batch_id`,`komoditi`,`plant_code`,`period`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
